version: '3'
services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    restart: always

    ports:
      # HTTP
      - 9191:9191
    environment:
      NIFI_WEB_HTTP_PORT: 9191

    networks:
      - backend
networks:
  backend:
    external:
      name: proxy
      
      
version: '3.4'
services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - 27091:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - ./mongo_data:/data/db
    networks:
      - backend
networks:
  backend:
    external:
      name: proxy
